name: Spell Check

on:
  - push
  - pull_request

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # See: https://github.com/codespell-project/actions-codespell/blob/master/README.md
      - name: Spell check
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: als
